version: 0.2

phases:
  post_build:
    commands:
      # '/' 폴더의 내용물을 S3 버킷의 'latest/' 경로로 동기화합니다.
      # --delete 옵션은 이전에 업로드된 파일이 있다면 삭제하여 항상 최신 상태를 유지합니다.
      - aws s3 sync / s3://source-for-imagebuilder-app/latest/ --delete
      - echo "Starting EC2 Image Builder pipeline execution..."
      # 빌드된 파일을 S3에 올린 후, 이 파일을 사용할 Image Builder 파이프라인을 실행시킵니다.
      #- aws imagebuilder start-image-pipeline-execution --image-pipeline-arn "arn:aws:imagebuilder:ap-northeast-2:131571435824:image-pipeline/react-app-pipeline"

artifacts:
  files:
    - '**/*'

